config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'restaurants#index'

  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[index new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
# Definition for class model
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true,
                       inclusion: {
                         in: %w[chinese italian japanese french belgian]
                       }

  def to_s
    "#{name}, #{address}"
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true,
                     inclusion: { in: [0, 1, 2, 3, 4, 5] },
                     numericality: true
  validates :restaurant, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])

    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header container">
      <p class="text-left"><%= link_to '🏡 Back Home', :root %></p>
      <h1 class="text-center">Restaurant Review app 🍔</h1>
      <p class="text-right"><%= link_to '➕ Add new restaurant', new_restaurant_path %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <% @restaurants.each do |restaurant| %>
    <p><%= link_to restaurant, restaurant_path(restaurant) %></p>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <%= simple_form_for(@restaurant) do |f| %>
 <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: %w[chinese italian japanese french belgian] %>
  <%= f.submit "Add a restaurant", class: "btn btn-primary" %>
<% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h2><%= @restaurant.name %></h2>

  <p>Address: 📍 <%= @restaurant.address %></p>
  <p>Phone Number: ☎️ <%= @restaurant.phone_number %></p>
  <p>Category: 🌮 <%= @restaurant.category %></p>
</div>
<div class="container">
  <p><%= link_to '🖋 Write a review', new_restaurant_review_path(@restaurant) %></p>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <%= simple_form_for [@restaurant, @review], url: restaurant_reviews_path, method: :post do |f| %>
    <% if @review.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @review.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.input :content %>
    <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
    <%= f.submit "Add review", class: "btn btn-primary" %>
  <% end %>
</div>